if(POLICY CMP0067)
    cmake_policy(SET CMP0067 NEW)
endif()
if(NOT _mkl_FOUND)
    if(NOT MKL_DIR)
        set(MKL_DIR "/opt/intel/oneapi/mkl/latest/lib/cmake/mkl")
    endif()
    find_package(MKL CONFIG REQUIRED PATHS $ENV{MKLROOT})
    if(MKL_FOUND)
        set(_mkl_FOUND TRUE BOOL "Flag to indicate that oneMKL has been configured once using this module")
        message(STATUS "oneMKL found")
        message(STATUS "${MKL_IMPORTED_TARGETS}")
    else()
        message(WARNING "oneMKL not found. Please make sure it's in your PATH")
    endif()
endif()

