networks:
  traefik-public:
    external: true

services:
  doxygen:
    image: ${IMAGE_FRONTEND}
    networks:
      - traefik-public
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${APP_NAME}-doxygen-http.rule=Host(`${HOST_URL?Variable not set}`)
        - traefik.http.routers.${APP_NAME}-doxygen-http.entrypoints=http
        - traefik.http.routers.${APP_NAME}-doxygen-http.middlewares=https-redirect,gzip
        - traefik.http.routers.${APP_NAME}-doxygen-http.service=${APP_NAME}-doxygen
        - traefik.http.routers.${APP_NAME}-doxygen-https.rule=Host(`${HOST_URL?Variable not set}`)
        - traefik.http.routers.${APP_NAME}-doxygen-https.entrypoints=https
        - traefik.http.routers.${APP_NAME}-doxygen-https.tls=true
        - traefik.http.routers.${APP_NAME}-doxygen-https.tls.certresolver=le
        - traefik.http.routers.${APP_NAME}-doxygen-https.middlewares=gzip
        - traefik.http.routers.${APP_NAME}-doxygen-https.service=${APP_NAME}-doxygen
        - traefik.http.services.${APP_NAME}-doxygen.loadbalancer.server.port=80
